# Exercise 6: Reading Tabular Data into DataFrames

## Aim: Learn what DataFrames are and practice using them.

### Issues covered:
- Importing the `pandas` library
- Using `pandas` to load a simple CSV data set
- Get information about the DataFrames we make

## 1. Let's import `pandas` and make some DataFrames.

Import `pandas`, then create a dataframe using the `data/weather.csv` file and print it out.

In [1]:
import pandas as pd

Create a new dataframe which indexes by `Date` and print it.

In [84]:
frame = pd.read_csv('/home/users/train023/my-ics-work/python-intro/data/weather.csv', index_col = 'Date')
frame

             Time  Temp  Rainfall
Date
2014-01-01  00:00  2.34      4.45
2014-01-01  12:00  6.70      8.34
2014-01-02  00:00 -1.34     10.25

## 2. Let's practice using some dataframe methods.

What is the memory usage of the dataframe in bytes?

In [85]:
frame.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 2014-01-01 to 2014-01-02
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Time      3 non-null      object
 1   Temp      3 non-null      float64
 2   Rainfall  3 non-null      float64
dtypes: float64(2), object(1)
memory usage: 96.0+ bytes

What command can you use to find the dataframe's column names?

In [86]:
frame.columns

Index(['Time', 'Temp', 'Rainfall'], dtype='object')

Swap the rows and columns and `print` the result.

frame = frame.T
frame.head()

Find the mean and standard deviation of the weather data.

In [72]:
avg = frame.agg({
    'Temp' : 'mean',
    'Rainfall' : 'mean',
})
avg

Temp        2.566667
Rainfall    7.680000
dtype: float64

In [73]:
stdv = frame.agg({
        'Temp' : 'std',
    'Rainfall' : 'std',
})
stdv

Temp        4.024790
Rainfall    2.955791
dtype: float64

## 3. Extension: Some Dataframe Challenges

1. Find the first three rows of data in `data/americas_gdp.csv` using `head()`.

In [74]:
america = pd.read_csv('/home/users/train023/my-ics-work/python-intro/data/americas_gdp.csv')
america.head()

,continent,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0,Americas,Argentina,5911.315053,6856.856212,7133.166023,8052.953021,9443.038526,10079.026740,8997.897412,9139.671389,9308.418710,10967.281950,8797.640716,12779.379640
1,Americas,Bolivia,2677.326347,2127.686326,2180.972546,2586.886053,2980.331339,3548.097832,3156.510452,2753.691490,2961.699694,3326.143191,3413.262690,3822.137084
2,Americas,Brazil,2108.944355,2487.365989,3336.585802,3429.864357,4985.711467,6660.118654,7030.835878,7807.095818,6950.283021,7957.980824,8131.212843,9065.800825
3,Americas,Canada,11367.161120,12489.950060,13462.485550,16076.588030,18970.570860,22090.883060,22898.792140,26626.515030,26342.884260,28954.925890,33328.965070,36319.235010
4,Americas,Chile,3939.978789,4315.622723,4519.094331,5106.654313,5494.024437,4756.763836,5095.665738,5547.063754,7596.125964,10118.053180,10778.783850,13171.638850

2. Find the last 3 **columns** of data.

_Hint: You may need to change your view of the data then you can use `tail()`._

In [75]:
america.tail(3)

,continent,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
22,Americas,United States,13990.482080,14847.127120,16173.145860,19530.365570,21806.035940,24072.632130,25009.559140,29884.350410,32003.932240,35767.433030,39097.099550,42951.65309
23,Americas,Uruguay,5716.766744,6150.772969,5603.357717,5444.619620,5703.408898,6504.339663,6920.223051,7452.398969,8137.004775,9230.240708,7727.002004,10611.46299
24,Americas,Venezuela,7689.799761,9802.466526,8422.974165,9541.474188,10505.259660,13143.950950,11152.410110,9883.584648,10733.926310,10165.495180,8605.047831,11415.80569

3. Use `help(data_americas.to_csv)` to figure out how writing to a CSV file works.

In [79]:
#help(america.to_csv)

4. Try writing to a CSV file using the code below (giving your own filename). Take a look in the data folder and check it's there.
```
data_americas.to_csv('data/new_file_name.csv')
```

In [81]:
america.to_csv('/home/users/train023/my-ics-work/python-intro/data/america_saved_to.csv')