# Exercise 7: More About Pandas DataFrames

## Aim: Learn how to select certain data from a `Pandas` DataFrame.

### Issues covered:
- Using `loc` and `iloc` to locate data in a dataframe
- Slicing dataframes
- Creating subsets and masks

## 1. Using `loc` and `iloc`

Create a dataframe called `data` from the CSV file `data/europe_gdp.csv` and index it by the `country` column.

In [1]:
import pandas as pd

In [2]:
a = pd.read_csv('/home/users/train023/my-ics-work/python-intro/data/europe_gdp.csv')
a.head()

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
0,Albania,1601.056136,1942.284244,2312.888958,2760.196931,3313.422188,3533.003910,3630.880722,3738.932735,2497.437901,3193.054604,4604.211737,5937.029526
1,Austria,6137.076492,8842.598030,10750.721110,12834.602400,16661.625600,19749.422300,21597.083620,23687.826070,27042.018680,29095.920660,32417.607690,36126.492700
2,Belgium,8343.105127,9714.960623,10991.206760,13149.041190,16672.143560,19117.974480,20979.845890,22525.563080,25575.570690,27561.196630,30485.883750,33692.605080
3,Bosnia and Herzegovina,973.533195,1353.989176,1709.683679,2172.352423,2860.169750,3528.481305,4126.613157,4314.114757,2546.781445,4766.355904,6018.975239,7446.298803
4,Bulgaria,2444.286648,3008.670727,4254.337839,5577.002800,6597.494398,7612.240438,8224.191647,8239.854824,6302.623438,5970.388760,7696.777725,10680.792820

Print out the GDP per capita for Belgium in 1957 (2nd column, 3rd row) using `iloc`.

_Hint: Remember that indexing starts from 0 in Python. You should get the value `9714.960623`._

In [20]:
belgium_gdpc = a.iloc[2,2]
belgium_gdpc

np.float64(9714.960623)

Use `loc` to print out GDP per capita for Belgium in 1957. You should get the same result as above.

In [30]:
#df.loc[df['shield'] > 6]
belgium_gdploc = a.loc[a['country'] =='Belgium','gdpPercap_1957']
belgium_gdploc

2    9714.960623
Name: gdpPercap_1957, dtype: float64

Print GDP per capita for `Switzerland` for all years using `:`.

In [57]:
switz = a.loc[a['country'] == 'Switzerland']
switz

,country,gdpPercap_1952,gdpPercap_1957,gdpPercap_1962,gdpPercap_1967,gdpPercap_1972,gdpPercap_1977,gdpPercap_1982,gdpPercap_1987,gdpPercap_1992,gdpPercap_1997,gdpPercap_2002,gdpPercap_2007
27,Switzerland,14734.23275,17909.48973,20431.0927,22966.14432,27195.11304,26982.29052,28397.71512,30281.70459,31871.5303,32135.32301,34480.95771,37506.41907

Print out GDP per capita in 1987 for all countries.

In [61]:
all_countries = a.iloc[:,0:1]
all_countries

                   country
0                  Albania
1                  Austria
2                  Belgium
3   Bosnia and Herzegovina
4                 Bulgaria
5                  Croatia
6           Czech Republic
7                  Denmark
8                  Finland
9                   France
10                 Germany
11                  Greece
12                 Hungary
13                 Iceland
14                 Ireland
15                   Italy
16              Montenegro
17             Netherlands
18                  Norway
19                  Poland
20                Portugal
21                 Romania
22                  Serbia
23         Slovak Republic
24                Slovenia
25                   Spain
26                  Sweden
27             Switzerland
28                  Turkey
29          United Kingdom

Print out a slice of the data frame which shows GDP for countries between Denmark to Iceland from 1982 to 1992.

Print out the last 3 columns for the last 3 rows of countries.

What are the maximum GDP values between 1997-2007 for the last 3 countries alphabetically?

## 2. Creating subsets and masks

Create a variable called `subset` which contains only the data for Hungary to Netherlands between 1962 and 1972. Print out the subset.

Return a dataframe of boolean (`True` or `False`) values showing where the GDP values are greater than 10000.

Create a boolean mask for the above and print the result of applying this to the subset.

What is the mean and standard deviation of the mask applied to this subset?

## 3. Extension Questions

1. Find the index of the maximum for each column of the dataset.

_Hint: You will need to make use of `idxmax()`._

2. Similarly, find the index of the minimum for each column of the dataset.

_Hint: You will need to make use of `idxmin()`._

3. Print out the median GDP per capita across all countries for each year.

_Hint: Use `median()`._